-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintDackling.

module PrintDackling where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsDackling

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsDackling.Ident where
  prt _ (AbsDackling.Ident i) = doc $ showString i
instance Print [AbsDackling.Expr' a] where
  prt 6 [] = concatD []
  prt 6 (x:xs) = concatD [prt 6 x, prt 6 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsDackling.Ident] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsDackling.Instr' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [AbsDackling.Pat' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (AbsDackling.Instructions' a) where
  prt i = \case
    AbsDackling.Program _ instrs -> prPrec i 0 (concatD [prt 0 instrs])

instance Print (AbsDackling.Instr' a) where
  prt i = \case
    AbsDackling.ExprInstr _ expr -> prPrec i 0 (concatD [prt 0 expr])
    AbsDackling.DefInstr _ def -> prPrec i 0 (concatD [prt 0 def])

instance Print (AbsDackling.Def' a) where
  prt i = \case
    AbsDackling.FunDef _ type_ id_ ids expr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 type_, doc (showString ":"), prt 0 id_, prt 0 ids, doc (showString "="), prt 0 expr])

instance Print (AbsDackling.Expr' a) where
  prt i = \case
    AbsDackling.EInt _ n -> prPrec i 6 (concatD [prt 0 n])
    AbsDackling.ETrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    AbsDackling.EFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    AbsDackling.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsDackling.ELExp _ lam -> prPrec i 6 (concatD [prt 0 lam])
    AbsDackling.EEmpty _ -> prPrec i 6 (concatD [doc (showString "[::]")])
    AbsDackling.EList _ exprs -> prPrec i 6 (concatD [doc (showString "[:"), prt 0 exprs, doc (showString ":]")])
    AbsDackling.EListAdd _ expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "::"), prt 6 expr2])
    AbsDackling.ENeg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsDackling.ENot _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsDackling.ECallFun _ id_ exprs -> prPrec i 5 (concatD [prt 0 id_, prt 6 exprs])
    AbsDackling.ECallLam _ lam exprs -> prPrec i 5 (concatD [prt 0 lam, prt 6 exprs])
    AbsDackling.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsDackling.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsDackling.EOr _ expr1 expr2 -> prPrec i 2 (concatD [prt 3 expr1, doc (showString "||"), prt 2 expr2])
    AbsDackling.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsDackling.ERel _ expr1 relop expr2 -> prPrec i 0 (concatD [prt 1 expr1, prt 0 relop, prt 0 expr2])
    AbsDackling.ELet _ type_ id_ ids expr1 expr2 -> prPrec i 0 (concatD [doc (showString "let"), prt 0 type_, doc (showString ":"), prt 0 id_, prt 0 ids, doc (showString "="), prt 0 expr1, doc (showString "in"), prt 0 expr2])
    AbsDackling.EIf _ expr1 expr2 expr3 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr1, doc (showString "then"), prt 0 expr2, doc (showString "else"), prt 0 expr3])
    AbsDackling.EMatch _ id_ pats -> prPrec i 0 (concatD [doc (showString "match"), prt 0 id_, doc (showString "with"), doc (showString "{"), prt 0 pats, doc (showString "}")])

instance Print (AbsDackling.Lam' a) where
  prt i = \case
    AbsDackling.ELFun _ type_ ids expr -> prPrec i 0 (concatD [doc (showString "\\"), prt 0 type_, prt 0 ids, doc (showString "->"), prt 6 expr, doc (showString "\\")])

instance Print (AbsDackling.Pat' a) where
  prt i = \case
    AbsDackling.PEmpty _ expr -> prPrec i 0 (concatD [doc (showString "|"), doc (showString "[::]"), doc (showString "->"), prt 0 expr])
    AbsDackling.PList _ id_1 id_2 expr -> prPrec i 0 (concatD [doc (showString "|"), prt 0 id_1, doc (showString "::"), prt 0 id_2, doc (showString "->"), prt 0 expr])

instance Print (AbsDackling.Type' a) where
  prt i = \case
    AbsDackling.Int _ -> prPrec i 0 (concatD [doc (showString "Int")])
    AbsDackling.Bool _ -> prPrec i 0 (concatD [doc (showString "Bool")])
    AbsDackling.FunType _ type_1 type_2 -> prPrec i 0 (concatD [prt 0 type_1, doc (showString "->"), prt 0 type_2])
    AbsDackling.FunArg _ type_1 type_2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 type_1, doc (showString "->"), prt 0 type_2, doc (showString ")")])
    AbsDackling.LiType _ type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 type_, doc (showString "]")])
    AbsDackling.Any _ -> prPrec i 0 (concatD [doc (showString "Any")])

instance Print (AbsDackling.AddOp' a) where
  prt i = \case
    AbsDackling.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    AbsDackling.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsDackling.MulOp' a) where
  prt i = \case
    AbsDackling.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsDackling.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    AbsDackling.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (AbsDackling.RelOp' a) where
  prt i = \case
    AbsDackling.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsDackling.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsDackling.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsDackling.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsDackling.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    AbsDackling.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])
